packages:
  - playground
  - docs
  - packages/*
  - examples/*

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - dprint
  - esbuild
  - simple-git-hooks

shellEmulator: true

trustPolicy: no-downgrade
